# Numpy Matrix Multiplication

In [1]:
import numpy as np

## Multiply（矩阵点乘）
先说说更简单的multiply，**如果两个维度完全一样的矩阵用multiply做乘法，那么它们只是进行对应位置元素之间的乘法**，得到一个同样维度的矩阵输出。这就是所谓的element-wise product, **也等同于运算符***

In [2]:
a = np.array([[0,1,2], [1,2,3], [3,4,5]])
b = np.array([[1,1,2], [2,2,1], [1,1,2]])

In [3]:
a

array([[0, 1, 2],
       [1, 2, 3],
       [3, 4, 5]])

In [4]:
b

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [5]:
print(np.multiply(a, b))

[[ 0  1  4]
 [ 2  4  3]
 [ 3  4 10]]


In [6]:
a*b

array([[ 0,  1,  4],
       [ 2,  4,  3],
       [ 3,  4, 10]])

**multiply只能对同样维度的矩阵之间相乘? too naive**.

相当于用b依次乘以a的每一lie

In [7]:
import numpy as np
a = np.array([[0, 1, 2], [1, 2, 3], [3, 4, 5]])
b = np.array([1, 2, 3])
print(np.multiply(a, b))

[[ 0  2  6]
 [ 1  4  9]
 [ 3  8 15]]


In [8]:
a[:, 2]*3

array([ 6,  9, 15])

In [9]:
b.shape

(3,)

记住，**multiply是满足交换律的**。（a和b互换位置结果不变）.

对于3x3的矩阵a，可以用3x1的矩阵与它相乘，也可以用1x3的矩阵与它相乘.

In [10]:
print(np.multiply(b, a))

[[ 0  2  6]
 [ 1  4  9]
 [ 3  8 15]]


还可以用它乘以一个常数

In [11]:
a = np.array([[0, 1, 2], [1, 2, 3], [3, 4, 5]])
print(np.multiply(a, 3))

[[ 0  3  6]
 [ 3  6  9]
 [ 9 12 15]]


## dot（矩阵叉乘）
dot就是矩阵叉乘，MxN矩阵乘以NxC矩阵会得到一个MxC的矩阵。对于**2D情况下的dot，等同于matmul，也等同于运算符@**。

In [12]:
a = np.array([[1, 0], [0, 2]])
b = np.array([[4, 1], [2, 2]])

In [13]:
a

array([[1, 0],
       [0, 2]])

In [14]:
b

array([[4, 1],
       [2, 2]])

In [15]:
np.dot(a, b)

array([[4, 1],
       [4, 4]])

In [16]:
a@b

array([[4, 1],
       [4, 4]])

**不满足交换律**

In [17]:
b@a

array([[4, 2],
       [2, 4]])

## matmul
在2D矩阵乘法中，其效果与dot一样

In [18]:
a = np.array([[ 1.73648178e-01, -9.84807753e-01,  0.00000000e+00,
         2.85330000e-04],
       [-9.84208313e-01, -1.73542480e-01,  3.48855737e-02,
        -1.36530000e-01],
       [-3.43555835e-02, -6.05781631e-03, -9.99391313e-01,
        -3.22680000e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [19]:
b = np.array([[-1.00000000e+00,  9.25887809e-08,  2.65197400e-06,
        -2.85244372e-04],
       [ 2.65358979e-06,  3.48918967e-02,  9.99391092e-01,
         3.22688646e-02],
       [ 0.00000000e+00,  9.99391092e-01, -3.48918967e-02,
         1.36529796e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [20]:
np.matmul(a, b)

array([[-0.17365079, -0.03436179, -0.98420764, -0.03154283],
       [ 0.98420785,  0.02880901, -0.17465664, -0.13708636],
       [ 0.03435557, -0.99899415,  0.02881644, -0.16890037],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [21]:
a.dot(b)

array([[-0.17365079, -0.03436179, -0.98420764, -0.03154283],
       [ 0.98420785,  0.02880901, -0.17465664, -0.13708636],
       [ 0.03435557, -0.99899415,  0.02881644, -0.16890037],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

在N维矩阵乘法中(N>=3)，体现出与dot不一样的算法

In [22]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])

In [23]:
a

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1.,

In [24]:
np.dot(a, c).shape

(9, 5, 7, 9, 5, 3)

In [25]:
np.matmul(a, c).shape

(9, 5, 7, 3)

## Summary
### Easy to Misuse
- The matrix multiplication in normal life, should be np.matmul(A, B) or A.dot(B) or A@B, not A*B(the same as np.multiply(A, B)